// Generated by Scripts/generate_domain_models.py; edit models/spec.py.
import Foundation

public struct Direction3D: Codable, Equatable, Sendable {
    public var x: Double
    public var y: Double
    public var z: Double
    public init(x: Double, y: Double, z: Double) {
        self.x = x
        self.y = y
        self.z = z
    }
}

public struct Displacement3D: Codable, Equatable, Sendable {
    public var x: Double
    public var y: Double
    public var z: Double
    public init(x: Double, y: Double, z: Double) {
        self.x = x
        self.y = y
        self.z = z
    }
}

public struct Dimensions3D: Codable, Equatable, Sendable {
    public var width: Length
    public var depth: Length
    public var height: Length
    public init(width: Length, depth: Length, height: Length) {
        self.width = width
        self.depth = depth
        self.height = height
    }
}

public struct ScheduleInterval: Codable, Equatable, Sendable {
    public var startMinute: Int
    public var endMinute: Int
    public var fraction: Ratio
    public init(startMinute: Int, endMinute: Int, fraction: Ratio) {
        self.startMinute = startMinute
        self.endMinute = endMinute
        self.fraction = fraction
    }
}

public struct DailySchedule: Codable, Equatable, Sendable {
    public var intervals: [ScheduleInterval]
    public init(intervals: [ScheduleInterval] = []) {
        self.intervals = intervals
    }
}

public struct ExtensionRecord: Codable, Equatable, Sendable {
    public let kind: String
    public let payloadVersion: Int
    public let payload: JSONValue
    public init(kind: String, payloadVersion: Int, payload: JSONValue) {
        self.kind = kind
        self.payloadVersion = payloadVersion
        self.payload = payload
    }
}

public struct Surface: Codable, Equatable, Sendable {
    public var id: UUID
    public var face: SurfaceFace
    public init(id: UUID, face: SurfaceFace) {
        self.id = id
        self.face = face
    }
}

public struct Opening: Codable, Equatable, Sendable {
    public var id: UUID
    public var surfaceID: UUID
    public var kind: OpeningKind
    public var offsetU: Length
    public var offsetV: Length
    public var width: Length
    public var height: Length
    public init(id: UUID, surfaceID: UUID, kind: OpeningKind, offsetU: Length, offsetV: Length, width: Length, height: Length) {
        self.id = id
        self.surfaceID = surfaceID
        self.kind = kind
        self.offsetU = offsetU
        self.offsetV = offsetV
        self.width = width
        self.height = height
    }
}

public struct Room: Codable, Equatable, Sendable {
    public var id: UUID
    public var name: String
    public var shape: ExtensionRecord
    public var northAngle: Angle
    public var surfaces: [Surface]
    public var openings: [Opening]
    public init(id: UUID, name: String, shape: ExtensionRecord, northAngle: Angle, surfaces: [Surface] = [], openings: [Opening] = []) {
        self.id = id
        self.name = name
        self.shape = shape
        self.northAngle = northAngle
        self.surfaces = surfaces
        self.openings = openings
    }
}

public struct Obstacle: Codable, Equatable, Sendable {
    public var id: UUID
    public var roomID: UUID
    public var name: String
    public var shape: ExtensionRecord
    public init(id: UUID, roomID: UUID, name: String, shape: ExtensionRecord) {
        self.id = id
        self.roomID = roomID
        self.name = name
        self.shape = shape
    }
}

public struct ProjectGeometry: Codable, Equatable, Sendable {
    public var rooms: [Room]
    public var obstacles: [Obstacle]
    public init(rooms: [Room] = [], obstacles: [Obstacle] = []) {
        self.rooms = rooms
        self.obstacles = obstacles
    }
}

public struct SamplePoint: Codable, Equatable, Sendable {
    public var id: UUID
    public var position: Position3D
    public init(id: UUID, position: Position3D) {
        self.id = id
        self.position = position
    }
}

public struct Seat: Codable, Equatable, Sendable {
    public var id: UUID
    public var roomID: UUID
    public var name: String
    public var position: Position3D
    public var samples: [SamplePoint]
    public init(id: UUID, roomID: UUID, name: String, position: Position3D, samples: [SamplePoint] = []) {
        self.id = id
        self.roomID = roomID
        self.name = name
        self.position = position
        self.samples = samples
    }
}

public struct HeatGain: Codable, Equatable, Sendable {
    public var sensible: ThermalPower
    public var convectiveFraction: Ratio
    public var latent: ThermalPower
    public init(sensible: ThermalPower, convectiveFraction: Ratio, latent: ThermalPower) {
        self.sensible = sensible
        self.convectiveFraction = convectiveFraction
        self.latent = latent
    }
}

public struct Occupant: Codable, Equatable, Sendable {
    public var id: UUID
    public var seatID: UUID
    public var activity: Activity
    public var clothing: Clothing
    public var heat: HeatGain
    public var schedule: DailySchedule
    public init(id: UUID, seatID: UUID, activity: Activity, clothing: Clothing, heat: HeatGain, schedule: DailySchedule) {
        self.id = id
        self.seatID = seatID
        self.activity = activity
        self.clothing = clothing
        self.heat = heat
        self.schedule = schedule
    }
}

public struct EquipmentGain: Codable, Equatable, Sendable {
    public var id: UUID
    public var roomID: UUID
    public var position: Position3D
    public var heat: HeatGain
    public var schedule: DailySchedule
    public init(id: UUID, roomID: UUID, position: Position3D, heat: HeatGain, schedule: DailySchedule) {
        self.id = id
        self.roomID = roomID
        self.position = position
        self.heat = heat
        self.schedule = schedule
    }
}

public struct Usage: Codable, Equatable, Sendable {
    public var seats: [Seat]
    public var occupants: [Occupant]
    public var equipment: [EquipmentGain]
    public init(seats: [Seat] = [], occupants: [Occupant] = [], equipment: [EquipmentGain] = []) {
        self.seats = seats
        self.occupants = occupants
        self.equipment = equipment
    }
}

public struct AirPort: Codable, Equatable, Sendable {
    public var id: UUID
    public var role: PortRole
    public var position: Position3D
    public var direction: Direction3D
    public var area: Area
    public var volumeFlow: VolumeFlow
    public var speed: Speed
    public var density: Density
    public init(id: UUID, role: PortRole, position: Position3D, direction: Direction3D, area: Area, volumeFlow: VolumeFlow, speed: Speed, density: Density) {
        self.id = id
        self.role = role
        self.position = position
        self.direction = direction
        self.area = area
        self.volumeFlow = volumeFlow
        self.speed = speed
        self.density = density
    }
}

public struct HVACDevice: Codable, Equatable, Sendable {
    public var id: UUID
    public var roomID: UUID
    public var name: String
    public var position: Position3D
    public var definition: ExtensionRecord
    public var ports: [AirPort]
    public var supplyTemperature: Temperature
    public init(id: UUID, roomID: UUID, name: String, position: Position3D, definition: ExtensionRecord, ports: [AirPort] = [], supplyTemperature: Temperature) {
        self.id = id
        self.roomID = roomID
        self.name = name
        self.position = position
        self.definition = definition
        self.ports = ports
        self.supplyTemperature = supplyTemperature
    }
}

public struct Control: Codable, Equatable, Sendable {
    public var id: UUID
    public var deviceID: UUID
    public var setpoint: Temperature
    public var sensorPosition: Position3D
    public var schedule: DailySchedule
    public init(id: UUID, deviceID: UUID, setpoint: Temperature, sensorPosition: Position3D, schedule: DailySchedule) {
        self.id = id
        self.deviceID = deviceID
        self.setpoint = setpoint
        self.sensorPosition = sensorPosition
        self.schedule = schedule
    }
}

public struct ThermalBoundary: Codable, Equatable, Sendable {
    public var mode: BoundaryMode
    public var temperature: Temperature?
    public var heatFlux: HeatFlux?
    public init(mode: BoundaryMode, temperature: Temperature? = nil, heatFlux: HeatFlux? = nil) {
        self.mode = mode
        self.temperature = temperature
        self.heatFlux = heatFlux
    }
}

public struct SurfaceCondition: Codable, Equatable, Sendable {
    public var surfaceID: UUID
    public var exposure: Exposure
    public var uValue: UValue
    public var boundary: ThermalBoundary
    public init(surfaceID: UUID, exposure: Exposure, uValue: UValue, boundary: ThermalBoundary) {
        self.surfaceID = surfaceID
        self.exposure = exposure
        self.uValue = uValue
        self.boundary = boundary
    }
}

public struct WindowCondition: Codable, Equatable, Sendable {
    public var openingID: UUID
    public var uValue: UValue
    public var shgc: Ratio
    public var shadingFactor: Ratio
    public init(openingID: UUID, uValue: UValue, shgc: Ratio, shadingFactor: Ratio) {
        self.openingID = openingID
        self.uValue = uValue
        self.shgc = shgc
        self.shadingFactor = shadingFactor
    }
}

public struct Envelope: Codable, Equatable, Sendable {
    public var surfaces: [SurfaceCondition]
    public var windows: [WindowCondition]
    public init(surfaces: [SurfaceCondition] = [], windows: [WindowCondition] = []) {
        self.surfaces = surfaces
        self.windows = windows
    }
}

public struct OpeningState: Codable, Equatable, Sendable {
    public var openingID: UUID
    public var openFraction: Ratio
    public init(openingID: UUID, openFraction: Ratio) {
        self.openingID = openingID
        self.openFraction = openFraction
    }
}

public struct RoomVentilation: Codable, Equatable, Sendable {
    public var roomID: UUID
    public var outdoorAir: VolumeFlow
    public var exhaustAir: VolumeFlow
    public var infiltration: VolumeFlow
    public var exfiltration: VolumeFlow
    public var density: Density
    public var openings: [OpeningState]
    public init(roomID: UUID, outdoorAir: VolumeFlow, exhaustAir: VolumeFlow, infiltration: VolumeFlow, exfiltration: VolumeFlow, density: Density, openings: [OpeningState] = []) {
        self.roomID = roomID
        self.outdoorAir = outdoorAir
        self.exhaustAir = exhaustAir
        self.infiltration = infiltration
        self.exfiltration = exfiltration
        self.density = density
        self.openings = openings
    }
}

public struct WeatherReference: Codable, Equatable, Sendable {
    public var relativePath: String
    public var sha256: String
    public init(relativePath: String, sha256: String) {
        self.relativePath = relativePath
        self.sha256 = sha256
    }
}

public struct Environment: Codable, Equatable, Sendable {
    public var representativeDate: String?
    public var timeZone: String?
    public var weather: WeatherReference?
    public var outdoorTemperature: Temperature
    public var outdoorHumidity: Ratio
    public var indoorHumidity: Ratio
    public init(representativeDate: String? = nil, timeZone: String? = nil, weather: WeatherReference? = nil, outdoorTemperature: Temperature, outdoorHumidity: Ratio, indoorHumidity: Ratio) {
        self.representativeDate = representativeDate
        self.timeZone = timeZone
        self.weather = weather
        self.outdoorTemperature = outdoorTemperature
        self.outdoorHumidity = outdoorHumidity
        self.indoorHumidity = indoorHumidity
    }
}

public struct TariffInterval: Codable, Equatable, Sendable {
    public var startMinute: Int
    public var endMinute: Int
    public var rate: EnergyRate
    public init(startMinute: Int, endMinute: Int, rate: EnergyRate) {
        self.startMinute = startMinute
        self.endMinute = endMinute
        self.rate = rate
    }
}

public struct Quote: Codable, Equatable, Sendable {
    public var id: UUID
    public var amount: Money
    public init(id: UUID, amount: Money) {
        self.id = id
        self.amount = amount
    }
}

public struct CostInputs: Codable, Equatable, Sendable {
    public var currency: String?
    public var tariffs: [TariffInterval]
    public var quotes: [Quote]
    public init(currency: String? = nil, tariffs: [TariffInterval] = [], quotes: [Quote] = []) {
        self.currency = currency
        self.tariffs = tariffs
        self.quotes = quotes
    }
}

public struct EvaluationInputs: Codable, Equatable, Sendable {
    public var cost: CostInputs
    public init(cost: CostInputs) {
        self.cost = cost
    }
}

public struct ScenarioInputs: Codable, Equatable, Sendable {
    public var usage: Usage
    public var hvac: [HVACDevice]
    public var controls: [Control]
    public var envelope: Envelope
    public var ventilation: [RoomVentilation]
    public var environment: Environment
    public init(usage: Usage, hvac: [HVACDevice] = [], controls: [Control] = [], envelope: Envelope, ventilation: [RoomVentilation] = [], environment: Environment) {
        self.usage = usage
        self.hvac = hvac
        self.controls = controls
        self.envelope = envelope
        self.ventilation = ventilation
        self.environment = environment
    }
}

public struct Scenario: Codable, Equatable, Sendable {
    public var id: UUID
    public var name: String
    public var inputs: ScenarioInputs
    public var evaluation: EvaluationInputs
    public init(id: UUID, name: String, inputs: ScenarioInputs, evaluation: EvaluationInputs) {
        self.id = id
        self.name = name
        self.inputs = inputs
        self.evaluation = evaluation
    }
}

public struct ProjectDocument: Codable, Equatable, Sendable {
    public var schemaVersion: Int
    public var id: UUID
    public var name: String
    public var spaceType: SpaceType
    public var lengthUnit: String
    public var coordinateSystem: String
    public var geometry: ProjectGeometry
    public var scenarios: [Scenario]
    public init(schemaVersion: Int = 2, id: UUID, name: String, spaceType: SpaceType, lengthUnit: String = "m", coordinateSystem: String = "rightHandedZUp", geometry: ProjectGeometry, scenarios: [Scenario] = []) {
        self.schemaVersion = schemaVersion
        self.id = id
        self.name = name
        self.spaceType = spaceType
        self.lengthUnit = lengthUnit
        self.coordinateSystem = coordinateSystem
        self.geometry = geometry
        self.scenarios = scenarios
    }
}

public struct ScenarioInputSnapshot: Codable, Equatable, Sendable {
    public let schemaVersion: Int
    public let projectID: UUID
    public let scenarioID: UUID
    public let lengthUnit: String
    public let coordinateSystem: String
    public let geometry: ProjectGeometry
    public let inputs: ScenarioInputs
    public let evaluation: EvaluationInputs
    public init(schemaVersion: Int = 2, projectID: UUID, scenarioID: UUID, lengthUnit: String = "m", coordinateSystem: String = "rightHandedZUp", geometry: ProjectGeometry, inputs: ScenarioInputs, evaluation: EvaluationInputs) {
        self.schemaVersion = schemaVersion
        self.projectID = projectID
        self.scenarioID = scenarioID
        self.lengthUnit = lengthUnit
        self.coordinateSystem = coordinateSystem
        self.geometry = geometry
        self.inputs = inputs
        self.evaluation = evaluation
    }
}

public struct RectangularRoom: Codable, Equatable, Sendable {
    public var dimensions: Dimensions3D
    public init(dimensions: Dimensions3D) {
        self.dimensions = dimensions
    }
}

public struct BoxObstacle: Codable, Equatable, Sendable {
    public var origin: Position3D
    public var dimensions: Dimensions3D
    public init(origin: Position3D, dimensions: Dimensions3D) {
        self.origin = origin
        self.dimensions = dimensions
    }
}

public struct SingleSplit: Codable, Equatable, Sendable {
    public var coolingCapacity: ThermalPower
    public var electricalPower: ElectricalPower
    public var cop: Ratio
    public init(coolingCapacity: ThermalPower, electricalPower: ElectricalPower, cop: Ratio) {
        self.coolingCapacity = coolingCapacity
        self.electricalPower = electricalPower
        self.cop = cop
    }
}
