# Generated by Scripts/generate_domain_models.py; edit models/spec.py.
from .primitives import *
from .json_value import FrozenJSON

class Position3D(WireModel):
    x: FloatValue
    y: FloatValue
    z: FloatValue

class Direction3D(WireModel):
    x: FloatValue
    y: FloatValue
    z: FloatValue

class Displacement3D(WireModel):
    x: FloatValue
    y: FloatValue
    z: FloatValue

class Dimensions3D(WireModel):
    width: Length
    depth: Length
    height: Length

class ScheduleInterval(WireModel):
    start_minute: IntValue
    end_minute: IntValue
    fraction: Ratio

class DailySchedule(WireModel):
    intervals: tuple[ScheduleInterval, ...]

class ExtensionRecord(WireModel):
    kind: str
    payload_version: IntValue
    payload: FrozenJSON

class Surface(WireModel):
    id: Identity
    face: SurfaceFace

class Opening(WireModel):
    id: Identity
    surface_id: Identity
    kind: OpeningKind
    offset_u: Length
    offset_v: Length
    width: Length
    height: Length

class Room(WireModel):
    id: Identity
    name: str
    shape: ExtensionRecord
    north_angle: Angle
    surfaces: tuple[Surface, ...]
    openings: tuple[Opening, ...]

class Obstacle(WireModel):
    id: Identity
    room_id: Identity
    name: str
    shape: ExtensionRecord

class ProjectGeometry(WireModel):
    rooms: tuple[Room, ...]
    obstacles: tuple[Obstacle, ...]

class SamplePoint(WireModel):
    id: Identity
    position: Position3D

class Seat(WireModel):
    id: Identity
    room_id: Identity
    name: str
    position: Position3D
    samples: tuple[SamplePoint, ...]

class HeatGain(WireModel):
    sensible: ThermalPower
    convective_fraction: Ratio
    latent: ThermalPower

class Occupant(WireModel):
    id: Identity
    seat_id: Identity
    activity: Activity
    clothing: Clothing
    heat: HeatGain
    schedule: DailySchedule

class EquipmentGain(WireModel):
    id: Identity
    room_id: Identity
    position: Position3D
    heat: HeatGain
    schedule: DailySchedule

class Usage(WireModel):
    seats: tuple[Seat, ...]
    occupants: tuple[Occupant, ...]
    equipment: tuple[EquipmentGain, ...]

class AirPort(WireModel):
    id: Identity
    role: PortRole
    position: Position3D
    direction: Direction3D
    area: Area
    volume_flow: VolumeFlow
    speed: Speed
    density: Density

class HVACDevice(WireModel):
    id: Identity
    room_id: Identity
    name: str
    position: Position3D
    definition: ExtensionRecord
    ports: tuple[AirPort, ...]
    supply_temperature: Temperature

class Control(WireModel):
    id: Identity
    device_id: Identity
    setpoint: Temperature
    sensor_position: Position3D
    schedule: DailySchedule

class ThermalBoundary(WireModel):
    mode: BoundaryMode
    temperature: Temperature | None = None
    heat_flux: HeatFlux | None = None

class SurfaceCondition(WireModel):
    surface_id: Identity
    exposure: Exposure
    u_value: UValue
    boundary: ThermalBoundary

class WindowCondition(WireModel):
    opening_id: Identity
    u_value: UValue
    shgc: Ratio
    shading_factor: Ratio

class Envelope(WireModel):
    surfaces: tuple[SurfaceCondition, ...]
    windows: tuple[WindowCondition, ...]

class OpeningState(WireModel):
    opening_id: Identity
    open_fraction: Ratio

class RoomVentilation(WireModel):
    room_id: Identity
    outdoor_air: VolumeFlow
    exhaust_air: VolumeFlow
    infiltration: VolumeFlow
    exfiltration: VolumeFlow
    density: Density
    openings: tuple[OpeningState, ...]

class WeatherReference(WireModel):
    relative_path: str
    sha256: str

class Environment(WireModel):
    representative_date: str | None = None
    time_zone: str | None = None
    weather: WeatherReference | None = None
    outdoor_temperature: Temperature
    outdoor_humidity: Ratio
    indoor_humidity: Ratio

class TariffInterval(WireModel):
    start_minute: IntValue
    end_minute: IntValue
    rate: EnergyRate

class Quote(WireModel):
    id: Identity
    amount: Money

class CostInputs(WireModel):
    currency: str | None = None
    tariffs: tuple[TariffInterval, ...]
    quotes: tuple[Quote, ...]

class EvaluationInputs(WireModel):
    cost: CostInputs

class ScenarioInputs(WireModel):
    usage: Usage
    hvac: tuple[HVACDevice, ...]
    controls: tuple[Control, ...]
    envelope: Envelope
    ventilation: tuple[RoomVentilation, ...]
    environment: Environment

class Scenario(WireModel):
    id: Identity
    name: str
    inputs: ScenarioInputs
    evaluation: EvaluationInputs

class ProjectDocument(WireModel):
    schema_version: Literal[2]
    id: Identity
    name: str
    space_type: SpaceType
    length_unit: Literal['m']
    coordinate_system: Literal['rightHandedZUp']
    geometry: ProjectGeometry
    scenarios: tuple[Scenario, ...]

class ScenarioInputSnapshot(WireModel):
    schema_version: Literal[2]
    project_id: Identity
    scenario_id: Identity
    length_unit: Literal['m']
    coordinate_system: Literal['rightHandedZUp']
    geometry: ProjectGeometry
    inputs: ScenarioInputs
    evaluation: EvaluationInputs

class RectangularRoom(WireModel):
    dimensions: Dimensions3D

class BoxObstacle(WireModel):
    origin: Position3D
    dimensions: Dimensions3D

class SingleSplit(WireModel):
    cooling_capacity: ThermalPower
    electrical_power: ElectricalPower
    cop: Ratio
