"""Structural source for Python wire models and their Swift mirrors.
Changes to persisted semantics require schema versioning and migration.
"""
MODELS = [
('Direction3D', [('x','Double'),('y','Double'),('z','Double')]),
('Displacement3D', [('x','Double'),('y','Double'),('z','Double')]),
('Dimensions3D', [('width','Length'),('depth','Length'),('height','Length')]),
('ScheduleInterval', [('startMinute','Int'),('endMinute','Int'),('fraction','Ratio')]),
('DailySchedule', [('intervals','[ScheduleInterval]')]),
('ExtensionRecord', [('kind','String'),('payloadVersion','Int'),('payload','JSONValue')]),
('Surface', [('id','UUID'),('face','SurfaceFace')]),
('Opening', [('id','UUID'),('surfaceID','UUID'),('kind','OpeningKind'),('offsetU','Length'),('offsetV','Length'),('width','Length'),('height','Length')]),
('Room', [('id','UUID'),('name','String'),('shape','ExtensionRecord'),('northAngle','Angle'),('surfaces','[Surface]'),('openings','[Opening]')]),
('Obstacle', [('id','UUID'),('roomID','UUID'),('name','String'),('shape','ExtensionRecord')]),
('ProjectGeometry', [('rooms','[Room]'),('obstacles','[Obstacle]')]),
('SamplePoint', [('id','UUID'),('position','Position3D')]),
('Seat', [('id','UUID'),('roomID','UUID'),('name','String'),('position','Position3D'),('samples','[SamplePoint]')]),
('HeatGain', [('sensible','ThermalPower'),('convectiveFraction','Ratio'),('latent','ThermalPower')]),
('Occupant', [('id','UUID'),('seatID','UUID'),('activity','Activity'),('clothing','Clothing'),('heat','HeatGain'),('schedule','DailySchedule')]),
('EquipmentGain', [('id','UUID'),('roomID','UUID'),('position','Position3D'),('heat','HeatGain'),('schedule','DailySchedule')]),
('Usage', [('seats','[Seat]'),('occupants','[Occupant]'),('equipment','[EquipmentGain]')]),
('AirPort', [('id','UUID'),('role','PortRole'),('position','Position3D'),('direction','Direction3D'),('area','Area'),('volumeFlow','VolumeFlow'),('speed','Speed'),('density','Density')]),
('HVACDevice', [('id','UUID'),('roomID','UUID'),('name','String'),('position','Position3D'),('definition','ExtensionRecord'),('ports','[AirPort]'),('supplyTemperature','Temperature')]),
('Control', [('id','UUID'),('deviceID','UUID'),('setpoint','Temperature'),('sensorPosition','Position3D'),('schedule','DailySchedule')]),
('ThermalBoundary', [('mode','BoundaryMode'),('temperature','Temperature?'),('heatFlux','HeatFlux?')]),
('SurfaceCondition', [('surfaceID','UUID'),('exposure','Exposure'),('uValue','UValue'),('boundary','ThermalBoundary')]),
('WindowCondition', [('openingID','UUID'),('uValue','UValue'),('shgc','Ratio'),('shadingFactor','Ratio')]),
('Envelope', [('surfaces','[SurfaceCondition]'),('windows','[WindowCondition]')]),
('OpeningState', [('openingID','UUID'),('openFraction','Ratio')]),
('RoomVentilation', [('roomID','UUID'),('outdoorAir','VolumeFlow'),('exhaustAir','VolumeFlow'),('infiltration','VolumeFlow'),('exfiltration','VolumeFlow'),('density','Density'),('openings','[OpeningState]')]),
('WeatherReference', [('relativePath','String'),('sha256','String')]),
('Environment', [('representativeDate','String?'),('timeZone','String?'),('weather','WeatherReference?'),('outdoorTemperature','Temperature'),('outdoorHumidity','Ratio'),('indoorHumidity','Ratio')]),
('TariffInterval', [('startMinute','Int'),('endMinute','Int'),('rate','EnergyRate')]),
('Quote', [('id','UUID'),('amount','Money')]),
('CostInputs', [('currency','String?'),('tariffs','[TariffInterval]'),('quotes','[Quote]')]),
('EvaluationInputs', [('cost','CostInputs')]),
('ScenarioInputs', [('usage','Usage'),('hvac','[HVACDevice]'),('controls','[Control]'),('envelope','Envelope'),('ventilation','[RoomVentilation]'),('environment','Environment')]),
('Scenario', [('id','UUID'),('name','String'),('inputs','ScenarioInputs'),('evaluation','EvaluationInputs')]),
('ProjectDocument', [('schemaVersion','Version2'),('id','UUID'),('name','String'),('spaceType','SpaceType'),('lengthUnit','Metres'),('coordinateSystem','ZUp'),('geometry','ProjectGeometry'),('scenarios','[Scenario]')]),
('ScenarioInputSnapshot', [('schemaVersion','Version2'),('projectID','UUID'),('scenarioID','UUID'),('lengthUnit','Metres'),('coordinateSystem','ZUp'),('geometry','ProjectGeometry'),('inputs','ScenarioInputs'),('evaluation','EvaluationInputs')]),
('RectangularRoom', [('dimensions','Dimensions3D')]),
('BoxObstacle', [('origin','Position3D'),('dimensions','Dimensions3D')]),
('SingleSplit', [('coolingCapacity','ThermalPower'),('electricalPower','ElectricalPower'),('cop','Ratio')]),
]
