#!/usr/bin/env python3
"""Generate structural models only; domain behavior lives in separate files."""
import sys, re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root / 'Backend/src'))
from simunow_worker.models.spec import MODELS

def snake(name):
    return re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name).lower()

def py_type(t):
    if t.endswith('?'): return py_type(t[:-1]) + ' | None'
    if t.startswith('['): return 'tuple[' + py_type(t[1:-1]) + ', ...]'
    return {'Double':'FloatValue','Int':'IntValue','UUID':'Identity','String':'str',
            'JSONValue':'FrozenJSON','Version2':"Literal[2]",'Metres':"Literal['m']",
            'ZUp':"Literal['rightHandedZUp']"}.get(t,t)

def swift_type(t):
    return {'Version2':'Int','Metres':'String','ZUp':'String'}.get(t,t)

python = '# Generated by Scripts/generate_domain_models.py; edit models/spec.py.\nfrom .primitives import *\nfrom .json_value import FrozenJSON\n\nclass Position3D(WireModel):\n    x: FloatValue\n    y: FloatValue\n    z: FloatValue\n\n'
swift = '// Generated by Scripts/generate_domain_models.py; edit models/spec.py.\nimport Foundation\n\n'
for name, fields in MODELS:
    python += f'class {name}(WireModel):\n'
    for field,t in fields:
        python += f'    {snake(field)}: {py_type(t)}' + (' = None' if t.endswith('?') else '') + '\n'
    python += '\n'
    swift += f'public struct {name}: Codable, Equatable, Sendable {{\n'
    immutable = name in ('ScenarioInputSnapshot','ExtensionRecord')
    for field,t in fields:
        swift += f'    public {"let" if immutable else "var"} {field}: {swift_type(t)}\n'
    args = []
    for field,t in fields:
        default = ' = nil' if t.endswith('?') else ' = []' if t.startswith('[') else ''
        default = {'Version2':' = 2','Metres':' = "m"','ZUp':' = "rightHandedZUp"'}.get(t, default)
        args.append(f'{field}: {swift_type(t)}{default}')
    swift += '    public init(' + ', '.join(args) + ') {\n'
    for field,t in fields:
        swift += f'        self.{field} = {field}\n'
    swift += '    }\n}\n\n'
outputs = {root/'Backend/src/simunow_worker/models/domain.py':python,
           root/'Packages/SimuKit/Sources/SimuCore/Project/DomainModels.swift':swift}
check = '--check' in sys.argv
for path,content in outputs.items():
    content = content.rstrip() + '\n'
    if check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Generated model drift: {path.relative_to(root)}')
    else: path.write_text(content)
